name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - feature
      - enhancement
  - title: '🐛 Bug Fixes'
    labels:
      - bug
      - fix
      - bugfix
  - title: '🧰 Maintenance'
    labels:
      - chore
      - dependencies
      - refactor

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
no-changes-template: 'No changes since last release.'

version-resolver:
  major:
    labels:
      - major
      - breaking-change
  minor:
    labels:
      - minor
      - feature
  patch:
    labels:
      - patch
      - fix
      - bug
      - bugfix
  default: patch

template: |
  ## Summary

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
