name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
    collapse-after: 5
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
    collapse-after: 5
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
    collapse-after: 3
  - title: '📚 Documentation'
    labels:
      - 'docs'
      - 'documentation'
    collapse-after: 3
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'chore'
  default: patch
autolabeler:
  - label: 'feature'
    title:
      - '/^feat($$.*$$)?:/i'
  - label: 'fix'
    title:
      - '/^fix($$.*$$)?:/i'
  - label: 'chore'
    title:
      - '/^chore($$.*$$)?:/i'
  - label: 'docs'
    title:
      - '/^docs($$.*$$)?:/i'
  - label: 'breaking'
    title:
      - '/^.*!:/i'
template: |
  ## Changes

  $CHANGES
