name: Release Drafter

on:
  push:
    branches:
      - master
      - production
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest

    steps:
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v6.1.1
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
